### ISSUE TITLE
Bug ngày 20/10/2021

### ISSUE THREAD

**Issue by ghost** [duykhanhrc/duykhanhrc.github.io#1]
Nội dung "Build Selenium Automation Test in Java" (hình 1) không có chỗ chuyển tiền. Hình thức thanh toán giống như khóa học "Khóa Tự Học Automation Test" (hình 2). Tại sao đã có học phí nhưng vẫn khuyến khích người ta mời cà phê?
Hình 1:
![image](https://user-images.githubusercontent.com/89739556/138129222-b596588d-b91b-42f0-accf-7603ef9820f5.png)

Hình 2:
![image](https://user-images.githubusercontent.com/89739556/138129272-ebb1764e-f3b1-4d77-aea9-2a7140f1beb9.png)

**Comment by duykhanhrc** [comment]
Dip #2
