### ISSUE TITLE
blog: How To Get Text Of An Element In Selenium?

### ISSUE THREAD

**Issue by letienson987** [duykhanhrc/duykhanhrc.github.io#30]

**Comment by duykhanhrc** [comment]
Bug 1: Responsive error with some blogs, plz check and fix it

**Comment by letienson987** [comment]
I pushed a new commit to fix responsive for the footer of the blogs, plz review my code @duykhanhrc  @VuThiNhan

**Comment by VuThiNhan** [comment]
this issue has been checked and fixed.
![image](https://user-images.githubusercontent.com/95455437/201123976-ba23f8ca-8bda-49fa-923b-2ed96442c382.png)
@duykhanhrc

**Comment by duykhanhrc** [comment]
@VuThiNhan yes close  ít
