### ISSUE TITLE
blog how to verify title in selenium

### ISSUE THREAD

**Issue by letienson987** [duykhanhrc/duykhanhrc.github.io#38]

**Comment by VuThiNhan** [comment]
cam on anh

**Comment by VuThiNhan** [comment]
Scenario: TC001_Verify blog how to verify title in selenium
GIVEN how to home page
WHEN how to blog
AND drag down and check blog
THEN verify blog how to verify title in selenium is not broken
...
This blog is no issue

**Comment by VuThiNhan** [comment]
> Scenario: TC001_Verify blog how to verify title in selenium
> 
> GIVEN how to home page WHEN how to blog AND drag down and check blog THEN verify blog how to verify title in selenium is not broken ... This blog is no issue

**Comment by VuThiNhan** [comment]
Scenario: TC001_Verify how to verify title in selenium
GIVEN go to home page
WHEN go to blog
THEN verify how to verify title in selenium

**Comment by VuThiNhan** [comment]
I think this blog is no issue
