### ISSUE TITLE
what is the whitebox testing?

### ISSUE THREAD

**Issue by letienson987** [duykhanhrc/duykhanhrc.github.io#44]

**Comment by VuThiNhan** [comment]
The follow button has error
![image](https://user-images.githubusercontent.com/95455437/205447533-5f3890bb-ff7a-4cf6-b688-8381a916690c.png)

**Comment by VuThiNhan** [comment]
The problem has been resovled, plz recheck again
![image](https://user-images.githubusercontent.com/95455437/205492764-0191ec42-947a-46c0-9b8c-99fc2a93f472.png)
